
mysql-main:
    restart: always
    build: mysql
    volumes:
     - /docker/mysql/crontab:/docker/crontab:ro
     - /docker/mysql/entrypoint.sh:/docker/entrypoint.sh:ro
     - /docker/mysql/mysql-backup.sh:/docker/mysql-backup.sh:ro
     - /docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
     - /storage/mysql:/var/lib/mysql
     - /storage/mysql-backup:/mysql-backup
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=pwd159357
    command: /bin/bash /docker/entrypoint.sh

redis-main:
    restart: always
    build: redis
    volumes:
     - /docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro

web-tornado:
    restart: always
    build: tornado
    volumes:
     - /docker/tornado/entrypoint.sh:/docker/entrypoint.sh:ro
     - /storage/website:/website:ro
    links:
     - mysql-main
     - redis-main
    command: /bin/bash /docker/entrypoint.sh

web-nginx:
    restart: always
    build: nginx
    ports:
     - "80:80"
    volumes:
     - /docker/nginx/crontab:/docker/crontab:ro
     - /docker/nginx/entrypoint.sh:/docker/entrypoint.sh:ro
     - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - /docker/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
     - /storage/website:/website:ro
     - /storage/website-static:/storage:ro
     - /storage/nginx-log:/nginx-log
    links:
     - web-tornado
    command: /bin/bash /docker/entrypoint.sh
